FROM postgres:%%PG_VERSION%%

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
        postgresql-%%PG_VERSION%%-postgis-%%POSTGIS_VERSION%% \
        && rm -rf /var/lib/apt/lists/*
